language: "node_js"

dist: trusty

node_js:
  - "10.15.3"
  - "node"
  
cache:
    directories:
      - "$HOME/.npm"

before_script:
  - psql -c 'CREATE DATABASE "quick_credit_test";' -U postgres
  - psql -c "CREATE USER debayo WITH PASSWORD 'password';" -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - "npm run nyc"

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false